version: '3.8'
services:
  application:
    image: openjdk:21
    container_name: spring-app
    working_dir: /app
    restart: always
    depends_on:
      - database
    ports:
      - '8080:8080'
    volumes:
      - './build/libs/spring.jar:/app/spring.jar'
      - './log:/app/log'
    command: java -Xms512m -Xmx512m -jar spring.jar

  database:
    image: postgres:latest
    container_name: spring-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - spring-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  spring-db:
    external: true
