spring:
  datasource:
    url: ${POSTGRESQL_NAME}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PWD}
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블 생성 (drop -> create)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect