SET REFERENTIAL_INTEGRITY = FALSE;

TRUNCATE TABLE member;
TRUNCATE TABLE `group`;
TRUNCATE TABLE diary;
TRUNCATE TABLE diary_content;
TRUNCATE TABLE refresh_token;
TRUNCATE TABLE notification;
TRUNCATE TABLE comment;
TRUNCATE TABLE reply;
TRUNCATE TABLE group_member;

SET REFERENTIAL_INTEGRITY = TRUE;