name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Java 환경 세팅 (Amazon Corretto JDK 21 사용)
      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Build Backend (Spring Boot)
        run: |
          cd server  # server 디렉토리로 이동
          ./gradlew clean build  # Gradle 빌드 수행

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}    # EC2 서버 IP
          username: ${{ secrets.EC2_USER }}  # EC2 사용자명
          key: ${{ secrets.EC2_KEY }}      # SSH 개인 키
          port: 22
          script: |
            cd /home/ec2-user/app
            pkill -f 'java -jar' || echo "No app running"
            rm -rf *.jar
            scp ${{ github.workspace }}/server/build/libs/*.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
            nohup java -jar /home/ec2-user/app/*.jar --server.port=8080 > /dev/null 2>&1 &
